#!/bin/sh
#
#     ########################
#  ##############################
# ####                        ####
####    sxhkd hot key daemon    #### 
# ####                        ####
#  ##############################
#     ########################
#

#
## Quick Reference

# Directions: {n, e, u, a}

# move window: super +         Directions
# swap window: super + shift + Directions

# rotate tree:   super + r ;                Directions
# resize window: super + shift + r ;        Directions
# resize window: super + shift + ctrl + r ; Directions

# tiling and flags: super + t ;
#  - tiling:       t
#  - pseudo_tiled: s
#  - floating:     l
#  - fullscreen:   f
#  - flag locked:  l
#  - flag marked:  m
#  - flag private: p
#  - flag sticky:  s

# preselect: super+j ;
#  - direction:   neua
#  - ratio:       1-9
#  - cancel node: space
#  - cancel desk: d

#  visual adjustments: super + v ;
#  - redshift warmer:   g
#  - redshift migraine: d
#  - redshift reset:    f

#
#######################
##  session hotkeys  ##
#######################
#
# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

# Log out of session 
super + alt + q
	bspc quit

# lock session
ctrl + alt + l
	xset s activate

# quit/restart bspwm
super + alt + r
	bspc wm -r

# close and kill applications
super + {_,shift + }w
	bspc node -{c,k}


####################
####  PROGRAMS  ####
####################
#
# terminal emulator
super +{_,shift +,ctrl + }Return
	{ alacritty, urxvt, kitty }

# program launcher
super +{_,shift + } space
   sh $HOME/.config/rofi/bin/{launcher,runner}


# programs
super + d
	thunar

super + h
	firefox

super + k
	keepassxc

super + shift + s
  flameshot gui

# blue-light adjustments for migraine, *very* migraine, and revert-to-normal
super + v ; {g,d,f}
	redshift { -PO 2400, -PO 2200 -b 0.6, -x}


#
# tiling state
# -----------

# alternate between tiling and monocle layouts
super + m
	bspc desktop -l next

# set the window tiling state. ~
super + t ; {t,s,l,f}
	bspc node -t ~{tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + t ; {l,m,s,p}
	bspc node -g {locked,marked,sticky,private}

#
# state/flag-based movement
# -------------------------


# swap the current node and the biggest node
super + {_,shift + }g
	bspc node -s {biggest.local, biggest}

# swap the current node with the newest marked node
super + y
	bspc node -s newest.marked.local

# send the current node to the newest preselected node
super + ctrl + y
	bspc node -n last.!automatic

# send the newest marked node to the newest preselected node
super + alt + y
	bspc node newest.marked.local -n newest.!automatic.local


#
# Balance
#
# Balance/equalize tree from node
super + {_,ctrl + }l
	bspc node @/ {-B,-E}

# Balance from parent or brother node, for other options
super + shift + l ; {p, b, e}
	bspc node {@parent -B, @brother -B, @/ -E}

# rotate!
super + r ; {n,e,u,a}
	bspc node @/ --rotate {90,180,-180, -90}

# Mirror and flip leaves of tree
super + {minus,asterisk}
	bspc node @/ -F {horizontal,vertical}

#
# focus/swap
#

# focus the node in the given direction
super + {_,shift + }{n,e,u,a}
	bspc node -{f,s} {west,south,north,east}
super + {_,shift + }{Left,Down,Up,Right}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous desktop in the current monitor
super + {_,shift + }Tab
	bspc desktop -f {next,prev}.local
super + ctrl + {Right, Left}
	bspc desktop -f {next,prev}.local

# focus or send to the given desktop
super + {_,ctrl + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

# send and follow to the given desktops
super + alt + {1-9,0}
	bspc node -d '^{1-9,10}' --follow

# focus the most recent previous node/desktop
super + {grave,asciitilde}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

#
# preselect
#

# preselect the direction
super + j ; {n,e,u,a}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + j ; {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + j; space
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + j; d
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel



#
# move/resize
#

# Continuous input mode
# =====================
# the bindings on the left of the colon create a locked mode; exit with <esc>.

# resize a window in the given direction 
super + shift + r : {n,e,u,a}
	bspwm_smart_resize {west,south,north,east} 50

# resize a floating window in the given direction
super + ctrl + shift + r : {n,e,u,a}
	bspc node -v {-20 0,0 20,0 -20,20 0}


# deprecated; remove
# expand a window by moving one of its side outward
super + alt + {Left,Down,Up,Right}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {Left,Down,Up,Right}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# cancel the preselection for the focused desktop
super + ctrl + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel
