
[font]
size = 8.5

[font.normal]
family = "Monospace"

[window]
opacity = 0.98

[window.padding]
x = 5
y = 5

[env]
TERM = "xterm-256color"

[general]
import = ["/home/possum/.config/alacritty/themes/tempus-themes/tempus_night.toml"]
