import = ["/home/possum/.config/alacritty/themes/gruvbox_dark"]

[font]
size = 8.5

[font.normal]
family = "Monospace"

[window]
opacity = 0.95

[window.padding]
x = 5
y = 5

[env]
TERM = "xterm-256color"
