theme = "rose_pine_moon"

[editor]
color-modes = true
line-number = "relative"
cursorline = true
scrolloff = 8
bufferline = "multiple"

[editor.statusline]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]

[editor.cursor-shape]
select = "underline"

[editor.indent-guides]
render = true
character = "┊"

[editor.soft-wrap]
enable = true

[keys.normal]
# -- Saving my hands ------------
"'" =  "collapse_selection"
'#' = "flip_selections"
esc = ["collapse_selection", "keep_primary_selection"]

# -- Window mode 2 --------------
"minus".s = "jump_view_left"
"minus".t = "jump_view_down"
"minus".d = "jump_view_up"
"minus".h = "jump_view_right"
"minus".S = "swap_view_left"
"minus".T = "swap_view_down"
"minus".D = "swap_view_up"
"minus".H = "swap_view_right"
"minus".r = "rotate_view"
"minus".c = "hsplit"
"minus".v = "vsplit"
"minus".k = ":bc"
"minus".K = "wclose"
"minus".z = "wonly"

# -- User Mode: You Get One
## normal only
space.g = ":w"
space.c = "toggle_comments"
space.l = ":lsp-restart"

## duplicate these to select also
space.space = "flip_selections"
space.x = ["extend_line_below", "trim_selections"]

[keys.select]
'#' = "flip_selections"

# usermode but in select
space.space = "flip_selections"
space.x = ["extend_line_below", "trim_selections"]

