#!/bin/bash

if [ "$GDMSESSION" == "xfce" ]
then
  xflock4
  return
fi

# constants
imagepath=$WALLPAPER_DIR/xfce-101-no-logo.png
wrong_text="Incorrect."
verif_text=""

i3lock \
  -i $imagepath -M \
  -c 260012  \
  -e -k -p default  \
  --ring-color=260012  \
  --ringwrong-color=a50018  \
  --inside-color=26001201  \
  --insidever-color=26001201  \
  --insidewrong-color=26001201  \
  --keyhl-color=60012b  \
  --bshl-color=d11272  \
  --ring-width=5  \
  --wrong-text=$wrong_text \
  --verif-text=$verif_text \
  --time-str="%H:%M" \
  --date-str="%A, %d %b"\
  --indicator
