#!/bin/sh

export FZF_DEFAULT_COMMAND='rg --files --follow'

export FZF_DEFAULT_OPTS='
  -m
  --height 40%
  --reverse
  --info=inline
  '
export FZF_COMPLETION_DIR_COMMANDS="cd pushd rmdir tree"

# todo: alt_c command should include hidden folders but not gitignored ones
# due to "there is a hidden folder at the top of the tree in most of the folders i navigate regularly"
