#!/bin/sh

## one monitor only
bspc monitor -d I II III IV V VI VII VIII IX X

## window appearance
bspc config border_width            1
bspc config top_padding             30
bspc config window_gap              10
bspc config split_ratio             0.52

bspc config focused_border_color    "#DDB6F2"

# bspc config honor_size_hints        true
bspc config borderless_monocle      true
bspc config gapless_monocle         false

## window behavior
bspc config focus_follows_pointer   false
bspc config pointer_modifier        mod4

bspc config automatic_scheme        longest_side      ##longest_side, alternate, spiral
bspc config initial_polarity        second_child   ##first_child, second_child

# open whisker menu floating
bspc rule -a Wrapper-2.0 state=floating border=off focus=on

bspc rule -a Gimp-2.10 desktop='^8' state=floating follow=on
bspc rule -a Emacs desktop='^6' state=tiled follow=on
#bspc rule -a Galculator state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

bspc rule -a xfce4-panel layer=above
bspc rule -a polybar layer=above

## Autostart ------------------

# start up the environment :)
autostart-xsession &


