theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
bufferline = "multiple"

[editor.cursor-shape]
select = "underline"

[editor.indent-guides]
render = true
character = "┊"

[editor.lsp]
snippets = true

[keys.normal]
# rebinds for my fucking hands
'#' = "flip_selections"
 "'" = "collapse_selection"

space.space = "flip_selections"
space.g = ":write"
space.x = ["extend_line_below", "trim_selections"]

M.n = "rotate_selections_backward"
M.e = "rotate_selection_contents_backward"
M.u = "rotate_selection_contents_forward"
M.a = "rotate_selection_contents_forward"

M.q = "move_line_up"

[keys.select]
'#' = "flip_selections"
 "'" = "collapse_selection"

space.x = ["extend_line_below", "trim_selections"]
