theme = "fleet_dark"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
bufferline = "multiple"

[editor.cursor-shape]
select = "underline"

[editor.indent-guides]
render = true
character = "┊"

[keys.normal]
# rebinds for my fucking hands
"'" = "collapse_selection"
"A-'" = "flip_selections"

space.space = "flip_selections"
space.g = ":write"
space.x = ["extend_line_below", "trim_selections"]

M.n = "rotate_selections_backward"
M.e = "rotate_selection_contents_backward"
M.u = "rotate_selection_contents_forward"
M.a = "rotate_selection_contents_forward"

M.q = "move_line_up"

[keys.select]
space.x = ["extend_line_below", "trim_selections"]
## space mode: consider rearranging this heavily to separate out user modes
# b uffer picker
# f ile picker
# F at cwd
# d diagnostic picker
# D diagnostic picker workspace
# h select symbol references
# j umplist picker
# k show docs for item under cursor
# p aste clipboard after selections
# P aste clipboard before selections
# r ename symbol
# R eplace selections by clip content
# s ymbol picker
# S symbol picker workspace# ' last picker
# w indow
# y join+yank to clipboard
# Y yank main selection to clipboard
# / Global serach in workspace folder
# ? open command palette
