#!/bin/sh

lock=$HOME/.config/niri/scripts/niri-swaylock

/usr/bin/swayidle -w \
  before-sleep "$lock" \
  timeout 10 'if pgrep -x gtklock; then niri msg action power-off-monitors; fi' \
  timeout 300 "$lock" \
  timeout 301 'niri msg action power-off-monitors'
