# Aesthetic or death
colorscheme 'catppuccin_mocha'

# To begin

evaluate-commands %sh{
  kak-lsp --kakoune --session "$kak_session"
}
lsp-enable

# Plugins -----------------------------------------------------------
source "%val{config}/bundle/kak-bundle/rc/kak-bundle.kak"
bundle-noload kak-bundle https://git.sr.ht/~jdugan6240/kak-bundle

# Auto-pairing
bundle auto-pairs.kak https://github.com/alexherbo2/auto-pairs.kak 
enable-auto-pairs

# File tree buffer
bundle kakoune-filetree https://github.com/occivink/kakoune-filetree

# Selection expansion and manipulation
bundle kakoune-expand https://github.com/occivink/kakoune-expand
bundle kakoune-phantom-selection https://github.com/occivink/kakoune-phantom-selection
bundle kakoune-vertical-selection https://github.com/occivink/kakoune-vertical-selection

# Custom snippets
# bundle kakoune-snippets https://github.com/occivink/kakoune-snippets

# Modules -----------------------------------------------------------
require-module fandt

## Options ----------------------------------------------------------

# UI options
set-option global tabstop 2
set-option global indentwidth 2

set-option global scrolloff 5,3
set-option global ui_options terminal_assistant=cat terminal_status_on_top=true

add-highlighter global/word-wrap wrap -word -indent
add-highlighter global/show-matching show-matching

# ## line numbers: relative by default; absolute in insert mode.
add-highlighter global/number-lines number-lines -hlcursor -relative

## toggle absolute line numbers in insert mode
hook global -group relative-line-numbers ModeChange .*:insert %{
  add-highlighter -override window/number-lines number-lines -hlcursor
}
hook global -group relative-line-numbers ModeChange .*:insert:.* %{
  add-highlighter -override window/number-lines number-lines -hlcursor -relative
}

# Mappings ----------------------------------------------------------

# Normal mode -------------------------------------------------------

# Bindings to reduce injury
map global normal "'"     ";"       -docstring 'reduce selections to their cursor'
map global normal <#>     "<a-;>"   -docstring 'flip selection direction'
map global normal <minus>	"<a-:>"		-docstring 'ensure forward selection direction'
map global normal <esc>   ";,"      -docstring 'clear all selections to current cursor'
map global normal D 			"xd"			-docstring 'delete current line'

map global normal <a-%> '*%s<ret>'              -docstring "select all occurrences of selection"
map global normal <ret> ':expand<ret>'          -docstring 'expand selection to next outer region'

map global normal ^ ':enter_format_mode<ret>'   -docstring 'enter format mode'
map global normal m ':enter_match_mode<ret>'    -docstring 'enter match mode'
map global normal q ':enter_mirror_mode<ret>'   -docstring 'enter extend mode'
map global normal Q ':enter_surround_mode<ret>' -docstring 'enter surround mode'
map global normal v <a-i>                       -docstring 'select inner surrounding objects'
map global normal V <a-a>                       -docstring 'select outer surrounding objects'

# rebind macros
map global normal <a-q> q -docstring "replay recorded macro"
map global normal <a-Q> Q -docstring "start/end macro recording"

# increment and decrement numbers
map global normal <c-a> ':increment_selected_numbers %val{count}<ret>'
map global normal <c-x> ':decrement_selected_numbers %val{count}<ret>'

declare-user-mode vertical-selection
map global normal C ':enter-user-mode -lock vertical-selection<ret>' -docstring 'enter vertical-selection mode'
map global vertical-selection n C -docstring 'copy selection on line below'
map global vertical-selection e <a-C> -docstring 'copy selection on line above'
map global vertical-selection a 'C<a-c>' -docstring 'copy selection above and below'
map global vertical-selection N ':vertical-selection-down<ret>' -docstring 'copy all matching selections below'
map global vertical-selection E ':vertical-selection-up<ret>' -docstring 'copy all matching selections above'
map global vertical-selection A ':vertical-selection-up-and-down<ret>' -docstring 'copy all matching selections above and below'

# Goto mode ---------------------------------------------------------
map global goto n ':bn<ret>' -docstring 'go to next buffer'
map global goto p ':bp<ret>' -docstring 'go to previous buffer'

# Match mode --------------------------------------------------------
 
map global match s ':enter_surround_mode<ret>' -docstring 'enter surround mode'

# User mode ---------------------------------------------------------

map global user b ':open_buffer_picker<ret>'            -docstring 'open buffer picker' 
map global user c ':comment-line<ret>'                  -docstring 'comment line'
map global user C ':comment-block<ret>'                 -docstring 'comment block'
map global user f ':open_file_picker<ret>'              -docstring 'open file picker' 
map global user g ':w<ret>'                             -docstring 'writes file; :w'
map global user k ':show_lsp_hover_info<ret>'           -docstring 'show LSP docs for selection' 
map global user l ':enter_lsp_mode<ret>'                -docstring 'enter LSP mode'
map global user m ':open_document_symbol_picker<ret>'   -docstring 'open document symbol picker' 
map global user M ':open_workspace_symbol_picker<ret>'  -docstring 'open workspace symbol picker'
map global user o ':enter_letter_case_mode<ret>'        -docstring 'enter letter_case mode'
map global user v <v> -docstring 'enter view mode'
map global user V <V> -docstring 'enter view mode (locked)'
map global user y ':yank_selection_to_clipboard<ret>'    -docstring 'yank to terminal clipboard'

# Prompt mode ------------------------------------------------------------------

map global prompt <a-/> '%sh{dirname "$kak_bufname"}<a-!>/' -docstring 'buffer directory' 

# Add search flags
map global prompt <c-i> '<home>(?i)<end>'
map global prompt <c-s> '<home>(?S)<end>'
map global prompt <c-k> '<home>\Q<end>'

#Insert mode --------------------------------------------------------

map global insert <c-w> '<esc>bc' -docstring 'convenience shortcut to change previous word in insert mode'
map global insert <c-y> '<c-r>"' -docstring 'paste selection register (")'

# tabs for autocomplete
hook global InsertCompletionShow .* %{
  map window insert <tab> <c-n>
  map window insert <s-tab> <c-p>
  hook -once window InsertCompletionHide .* %{
    unmap window insert <tab>
    unmap window insert <s-tab>
  }
}

