# Aesthetic or death
colorscheme catppuccin_mocha

# Tabs and indents
set-option global tabstop 4
set-option global indentwidth 4

# keep one line and three columns displayed around the cursor
set-option global scrolloff 1,3

# highlighters
add-highlighter global/ number-lines -hlcursor
add-highlighter global/ wrap -word -indent

# mappings
map global normal '#' :comment-line<ret> -docstring 'comment line'
map global normal '<a-#>' :comment-block<ret> -docstring 'comment block'

