# vi:ft=yaml
# name: 'Tempus Spring'
# author: 'Protesilaos Stavrou (https://protesilaos.com)'
# description: 'Dark theme with a palette inspired by early spring colours (WCAG AA compliant)'

[colors.primary]
foreground = '#b5b8b7'
background = '#283a37'

[colors.cursor]
text = '#283a37'
cursor = '#b5b8b7'

[colors.selection]
text = '#283a37'
background = '#b5b8b7'

[colors.normal]
black = '#283a37'
red = '#ff8b5f'
green = '#5ec04d'
yellow = '#b0b01a'
blue = '#39bace'
magenta = '#e99399'
cyan = '#36c08e'
white = '#99afae'

[colors.bright]
black = '#2a453d'
red = '#e19e00'
green = '#73be0d'
yellow = '#c6a843'
blue = '#70afef'
magenta = '#d095e2'
cyan = '#3cbfaf'
white = '#b5b8b7'
