# vi:ft=yaml
# name: 'Tempus Fugit'
# author: 'Protesilaos Stavrou (https://protesilaos.com)'
# description: 'Light, pleasant theme optimised for long writing/coding sessions (WCAG AA compliant)'

[colors.primary]
foreground = '#4d595f'
background = '#fff5f3'

[colors.cursor]
text = '#fff5f3'
cursor = '#4d595f'

[colors.selection]
text = '#fff5f3'
background = '#4d595f'

[colors.normal]
black = '#4d595f'
red = '#c61a14'
green = '#357200'
yellow = '#825e00'
blue = '#1666b0'
magenta = '#a83884'
cyan = '#007072'
white = '#efe6e4'

[colors.bright]
black = '#796271'
red = '#b93f1a'
green = '#437520'
yellow = '#985900'
blue = '#485adf'
magenta = '#a234c0'
cyan = '#00756a'
white = '#fff5f3'
