#!/bin/sh
#
#     ########################
#  ##############################
# ####                        ####
####    sxhkd hot key daemon    #### 
# ####                        ####
#  ##############################
#     ########################
#

#
#######################
##  session hotkeys  ##
#######################
#
# make sxhkd reload its configuration files:
super + Escape
	pkill -USR1 -x sxhkd

# Log out of session 
super + alt + q
	bspc quit

# lock session
ctrl + alt + l
	xset s activate

# quit/restart bspwm
super + alt + r
	bspc wm -r

# close and kill applications
super + {_,shift + }w
	bspc node -{c,k}


####################
####  PROGRAMS  ####
####################
#
# terminal emulator
super +{_,shift +,ctrl + }Return
	{ alacritty, urxvt, kitty }

# program launcher
super +{_,shift + } space
   sh $HOME/.config/rofi/bin/{launcher,runner}


# programs
super + d
	thunar

super + h
	firefox

super + j
	~/.joplin/Joplin.AppImage

super + k
	keepassxc

super + v
	code

super + shift + s
  flameshot gui

super + r
	redshift -PO 2400 
super + shift + r
	redshift -PO 2200 -b 0.6
super + ctrl + r
	redshift -x

#
# state/flags
#

# set the window state
super + {t,shift + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {m,x,q,z}
	bspc node -g {marked,locked,sticky,private}

#
# state/flag-based movement
#

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

# swap the current node and the biggest node
super + {_,shift + }g
	bspc node -s {biggest.local, biggest}

# send the current node to the newest preselected node
super + y
	bspc node -n last.!automatic

# swap the current node with the newest marked node
super + ctrl + y
	bspc node -s newest.marked.local

# send the newest marked node to the newest preselected node
super + alt + y
	bspc node newest.marked.local -n newest.!automatic.local


#
# Balance
#
# Balance tree
super + l
	bspc node @/ -B

super + shift + l
	bspc node @parent -B

# Balance brother node. If you do this on biggest window of the desktop, it usually means balancing all windows with except the biggest.
super + alt + l
	bspc node @brother -B
	
# Undo balancing (equalize windows)
super + ctrl + l
	bspc node @/ -E

# Mirror and flip leaves of tree
super + {minus,asterisk}
	bspc node @/ -F {horizontal,vertical}


#
# focus/swap
#

# focus the node in the given direction
super + {_,shift + }{n,e,u,a}
	bspc node -{f,s} {west,south,north,east}
super + {_,shift + }{Left,Down,Up,Right}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous node in the current desktop
super + {_,shift + }c
	bspc node -f {next,prev}.local

# focus the next/previous desktop in the current monitor
# super + bracket{left,right}
super + {_,shift + }Tab
	bspc desktop -f {next,prev}.local

super + ctrl + {Right, Left}
	bspc desktop -f {next,prev}.local

# focus the last node/desktop
super + {grave,asciitilde}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

alt + {_,shift + }Tab
	bspc wm -h off; \
	bspc node {older, newer} -f; \
	bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

# send and follow to the given desktops
super + alt + {1-9,0}
	bspc node -d '^{1-9,10}' --follow
#
# preselect
#

# preselect the direction
super + ctrl + {n,e,u,a}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
#

# expand a window by moving one of its side outward
super + alt + {Left,Down,Up,Right}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {Left,Down,Up,Right}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + ctrl + shift + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}
