## Options ----------------------------------------------------------
set-option global grepcmd 'rg --column --smart-case --sort path'

# UI options
set-option global tabstop 4
set-option global indentwidth 4

set-option global scrolloff 5,10
set-option global ui_options terminal_assistant=cat terminal_status_on_top=true

# Apply formatting by default to every buffer, named or not
hook global BufCreate ^.*$ %{
	add-highlighter buffer/show-matching show-matching
	add-highlighter buffer/word-wrap wrap -word -indent

    add-highlighter buffer/numbers number-lines -hlcursor -relative

	# relative-insert-numbers: Switch between relative and absolute number-lines
	# NORMAL mode uses relative numbers
	# INSERT mode uses absolute numbers
    hook buffer -group relative-insert-numbers ModeChange .*:insert %{
        add-highlighter -override buffer/numbers number-lines -hlcursor 
    }

    hook buffer -group relative-insert-numbers ModeChange .*:insert:.* %{
        add-highlighter -override buffer/numbers number-lines -hlcursor -relative
    }
}

# Mappings ----------------------------------------------------------

# Normal mode 
map global normal <#>     "<a-;>"                    -docstring 'flip selection direction'
map global normal <a-#>   "<a-:>"                    -docstring 'ensure forward selection direction'
map global normal <esc>   ";,"                       -docstring 'clear all selections to current cursor'
map global normal D       "xd"                       -docstring 'delete current line'

map global normal <a-%>   '*%s<ret>'                 -docstring "select all occurrences of selection"
map global normal <ret>   ':expand<ret>'             -docstring 'expand selection to next outer region'
map global normal <minus> ':enter-window-mode<ret>'  -docstring 'enter window mode: tmux movements'
map global normal "'"     ':enter_mirror_mode<ret>'  -docstring 'enter mirror mode: expand and surround selections'
map global normal =       ':enter_math_mode<ret>'    -docstring 'enter math mode: increment and decrement counts'

# map m to <a-a/i>, and replace v with m's previous functionality; view mode moves to userspace
map global normal m       <a-i>                      -docstring 'select inner surrounding objects'
map global normal M       <a-a>                      -docstring 'select outer surrounding objects'
map global normal v       m                          -docstring 'select to next matching character'
map global normal V       M                          -docstring 'extend to next matching character'
map global normal <a-v>   <a-m>                      -docstring 'select to previous matching character'
map global normal <a-V>   <a-M>                      -docstring 'extend to previous matching character'

# extend full-line selection up and down: https://discuss.kakoune.com/t/improved-and-consistent-line-selection-with-x-and-a-x/2243
map global normal <a-X> %{<a-:><a-;><a-H>Kx} -docstring 'extend lines upwards' 
map global normal X %{<a-:>F<ret>x}          -docstring 'extend lines downwards' 

# increment and decrement numbers
map global normal <c-a> ':increment_selected_numbers %val{count}<ret>'
map global normal <c-x> ':decrement_selected_numbers %val{count}<ret>'

# clipboard.kak: clipboard sync on explicit yank
hook global NormalKey y clipboard-sync

# Goto mode ---------------------------------------------------------
map global goto n '<esc>:bn<ret>' -docstring 'go to next buffer'
map global goto p '<esc>:bp<ret>' -docstring 'go to previous buffer'

map global view z v -docstring 'center cursor (vertically)'

# User mode ---------------------------------------------------------
## w g d f b q l u o y
#  r s t h k j n e a i
#  x c m p v  ' , . 

map global user b     ':open_buffer_picker<ret>'             -docstring 'open buffer picker' 
map global user c     ':comment-line<ret>'                   -docstring 'comment line'
map global user <a-c> ':comment-block<ret>'                  -docstring 'comment block'
map global user C     '<a-C>C'                               -docstring 'copy selection up and down'
map global user f     ':open_file_picker<ret>'               -docstring 'open file picker' 
map global user g     ':w<ret>'                              -docstring 'writes file; :w'
map global user o     ':enter_letter_case_mode<ret>'         -docstring 'enter letter_case mode'
map global user p     ':enter-phantom-select-mode<ret>'      -docstring 'enter phantom selection mode'
map global user s     ':vertical-selection-down<ret>'        -docstring 'copy matching selections below' 
map global user <a-s> ':vertical-selection-up<ret>'          -docstring 'copy matching selections above' 
map global user S     ':vertical-selection-up-and-down<ret>' -docstring 'copy matching selections above and below' 
map global user z     <v>                                    -docstring 'enter view mode'
map global user Z     <V>                                    -docstring 'enter view mode (locked)'
# d, k, l, m are currently reserved for lsp actions

# Prompt mode ------------------------------------------------------------------

map global prompt <a-/> '%sh{dirname "$kak_bufname"}<a-!>/' -docstring 'print current buffer directory' 

# Add search flags
map global prompt <a-i> '<home>(?i)<end>' -docstring 'case-insensitive search'
map global prompt <a-s> '<home>(?S)<end>' -docstring "prevents '.' from matching newlines"
map global prompt <a-q> '<home>\Q<end>'   -docstring "begins a quoted (literal) sequence. End with '\E'"

#Insert mode --------------------------------------------------------

map global insert <c-w> '<esc>bc' -docstring 'delete last word: readline-equivalent behavior'
map global insert <c-y> '<c-r>"'  -docstring 'paste selection register (")'


# tabs for autocomplete
hook global InsertCompletionShow .* %{
    map window insert <tab> <c-n>
    map window insert <s-tab> <c-p>
    hook -once window InsertCompletionHide .* %{
        unmap window insert <tab>
        unmap window insert <s-tab>
    }
}

# User modes --------------------------------------------------------
declare-user-mode window
define-command enter-window-mode %{ enter-user-mode window}
hook global ModuleLoaded tmux %{ require-module tmux-windowing }

# Plugins -----------------------------------------------------------
source "%val{config}/bundle/kak-bundle/rc/kak-bundle.kak"
bundle-noload kak-bundle https://git.sr.ht/~jdugan6240/kak-bundle

# colorscheme
bundle-noload kakoune-mysticaltutor "https://github.com/caksoylar/kakoune-mysticaltutor" '' %{
    mkdir -p "${kak_config}/colors/plugin"
    ln -sf "${kak_opt_bundle_path}/kakoune-mysticaltutor/mysticaltutor.kak" "${kak_config}/colors/plugin/"
}
try %{ colorscheme mysticaltutor }

# Auto-pairing
bundle auto-pairs.kak https://github.com/alexherbo2/auto-pairs.kak %{
    enable-auto-pairs
}

# File tree buffer
# bundle kakoune-filetree https://github.com/occivink/kakoune-filetree
bundle kaktree https://github.com/possumvibes/kaktree %{
    hook global WinSetOption filetype=kaktree %{
        remove-highlighter buffer/numbers
        remove-hooks buffer relative-insert-numbers
        remove-highlighter buffer/wrap
        remove-highlighter  buffer/show-matching
    }
    kaktree-enable
} 

# Selection expansion and manipulation
bundle kakoune-expand https://github.com/occivink/kakoune-expand
bundle kakoune-phantom-selection https://github.com/occivink/kakoune-phantom-selection %{
    declare-user-mode phantom-selection
    map global phantom-selection a ':phantom-selection-add-selection<ret>' -docstring 'add selection to phantom list'
    map global phantom-selection A ':phantom-selection-select-all<ret>' -docstring 'select all phantoms'
    map global phantom-selection n ':phantom-selection-iterate-next<ret>' -docstring 'iterate to next phantom'
    map global phantom-selection e ':phantom-selection-iterate-prev<ret>' -docstring 'iterate to previous phantom'
    map global phantom-selection j ':phantom-selection-clear<ret>' -docstring 'clear phantom selections'

    define-command enter-phantom-select-mode %{ enter-user-mode phantom-selection }
}

bundle kakoune-vertical-selection https://github.com/occivink/kakoune-vertical-selection %{
    map global normal ^     ':vertical-selection-down<ret>'   -docstring 'copy matching selections below' 
    map global normal <a-^> ':vertical-selection-up<ret>'     -docstring 'copy matching selections above' 
}

bundle kakoune-fandt https://gitlab.com/listentolist/kakoune-fandt %{
    require-module fandt
} 

# Custom snippets
# bundle kakoune-snippets https://github.com/occivink/kakoune-snippets
## LSP setup
evaluate-commands %sh{
    if command -v kak-lsp &> /dev/null; then 
        kak-lsp --kakoune --session "$kak_session"
    fi
}

# Filetype hooks
hook global WinSetOption filetype=rust %{
    lsp-init
}

hook global WinSetOption filetype=markdown %{
    # Markdown uses tab width 2

    set-option buffer tabstop 2
    set-option buffer indentwidth 2

    lsp-init
}
